//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.24 at 09:26:08 pm UTC 
//


package api.mnoutilityservice.miniproject.com.activities;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the api.mnoutilityservice.miniproject.com.activities package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: api.mnoutilityservice.miniproject.com.activities
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BulkAirtimePurchaseRequest }
     * 
     */
    public BulkAirtimePurchaseRequest createBulkAirtimePurchaseRequest() {
        return new BulkAirtimePurchaseRequest();
    }

    /**
     * Create an instance of {@link AirtimeTransferRequest }
     * 
     */
    public AirtimeTransferRequest createAirtimeTransferRequest() {
        return new AirtimeTransferRequest();
    }

    /**
     * Create an instance of {@link TransactionInfo }
     * 
     */
    public TransactionInfo createTransactionInfo() {
        return new TransactionInfo();
    }

    /**
     * Create an instance of {@link TransactionHistoryRequest }
     * 
     */
    public TransactionHistoryRequest createTransactionHistoryRequest() {
        return new TransactionHistoryRequest();
    }

    /**
     * Create an instance of {@link AccountInfo }
     * 
     */
    public AccountInfo createAccountInfo() {
        return new AccountInfo();
    }

    /**
     * Create an instance of {@link AirtimeTransferResponse }
     * 
     */
    public AirtimeTransferResponse createAirtimeTransferResponse() {
        return new AirtimeTransferResponse();
    }

    /**
     * Create an instance of {@link BalanceCheckingRequest }
     * 
     */
    public BalanceCheckingRequest createBalanceCheckingRequest() {
        return new BalanceCheckingRequest();
    }

    /**
     * Create an instance of {@link PurchaseAirtimeResponse }
     * 
     */
    public PurchaseAirtimeResponse createPurchaseAirtimeResponse() {
        return new PurchaseAirtimeResponse();
    }

    /**
     * Create an instance of {@link PurchaseAirtimeRequest }
     * 
     */
    public PurchaseAirtimeRequest createPurchaseAirtimeRequest() {
        return new PurchaseAirtimeRequest();
    }

    /**
     * Create an instance of {@link BalanceCheckingResponse }
     * 
     */
    public BalanceCheckingResponse createBalanceCheckingResponse() {
        return new BalanceCheckingResponse();
    }

    /**
     * Create an instance of {@link TransactionHistoryResponse }
     * 
     */
    public TransactionHistoryResponse createTransactionHistoryResponse() {
        return new TransactionHistoryResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link BulkAirtimePurchaseResponse }
     * 
     */
    public BulkAirtimePurchaseResponse createBulkAirtimePurchaseResponse() {
        return new BulkAirtimePurchaseResponse();
    }

}
